### ISSUE TITLE
Unsupported Mapper 163

### ISSUE THREAD

**Issue by 925691226** [FIX94/fixNES#7]
fixNES Alpha v1.2.7
File Type: NES
Full Path: D:\Emulator\RetroArch\downloads\Nes\sanguomengjiang.nes
Audio: 16-bit Short Output at 223721Hz
Used Mapper: 163
PRG: 0x200000 bytes PRG RAM: 0x2000 bytes CHR: 0x0 bytes
Unsupported Mapper 163!
Mapper init failed!
Press enter to exit
[sanguomengjiang.zip](https://github.com/FIX94/fixNES/files/3695148/sanguomengjiang.zip)

**Comment by 925691226** [comment]
![20191007090424](https://user-images.githubusercontent.com/24504943/66279125-e348de80-e8e1-11e9-9715-d14de7d8043d.png)
![20191007090653](https://user-images.githubusercontent.com/24504943/66279127-e47a0b80-e8e1-11e9-8dbc-51af9421f3cb.png)

**Comment by 925691226** [comment]
The mapper 163 amendment simulates the protection circuit of Nanjing cassette, and corrects the image of PromCRC-F52468E7.

**Comment by 925691226** [comment]
I hope it will help you.

**Comment by FIX94** [comment]
hey there, no clue if you will still read this anyways but I added support for this particular mapper in todays update, so it should work fine now.

**Comment by 925691226** [comment]
Thank you for your work, this is great.




---Original---
